- pkg:maven/org.lyranthe.prometheus/play24_2.11@0.8.1
- pkg:maven/org.lyranthe.prometheus/play24_2.11@0.8.1?classifier=sources
- pkg:maven/org.lyranthe.prometheus/play24_2.11@0.8.0
- pkg:maven/org.lyranthe.prometheus/play24_2.11@0.8.0?classifier=sources
- pkg:maven/org.lyranthe.prometheus/play24_2.11@0.7.0
- pkg:maven/org.lyranthe.prometheus/play24_2.11@0.7.0?classifier=sources
