- pkg:maven/io.fabric8.forge/devops@2.2.7
- pkg:maven/io.fabric8.forge/devops@2.2.7?classifier=sources
- pkg:maven/io.fabric8.forge/devops@2.2.6
- pkg:maven/io.fabric8.forge/devops@2.2.6?classifier=sources
- pkg:maven/io.fabric8.forge/devops@2.2.9
- pkg:maven/io.fabric8.forge/devops@2.2.9?classifier=sources
- pkg:maven/io.fabric8.forge/devops@2.2.8
- pkg:maven/io.fabric8.forge/devops@2.2.8?classifier=sources
- pkg:maven/io.fabric8.forge/devops@2.2.11
- pkg:maven/io.fabric8.forge/devops@2.2.11?classifier=sources
- pkg:maven/io.fabric8.forge/devops@2.2.10
- pkg:maven/io.fabric8.forge/devops@2.2.10?classifier=sources
