- pkg:maven/io.earcam.utilitarian/io.earcam.utilitarian.site.deploy.netlify@0.0.1
- pkg:maven/io.earcam.utilitarian/io.earcam.utilitarian.site.deploy.netlify@0.0.1?classifier=sources
- pkg:maven/io.earcam.utilitarian/io.earcam.utilitarian.site.deploy.netlify@1.0.0
- pkg:maven/io.earcam.utilitarian/io.earcam.utilitarian.site.deploy.netlify@1.0.0?classifier=sources
- pkg:maven/io.earcam.utilitarian/io.earcam.utilitarian.site.deploy.netlify@1.1.0
- pkg:maven/io.earcam.utilitarian/io.earcam.utilitarian.site.deploy.netlify@1.1.0?classifier=sources
