- pkg:maven/io.prometheus.jmx/jmx_prometheus_javaagent@0.3
- pkg:maven/io.prometheus.jmx/jmx_prometheus_javaagent@0.3?classifier=sources
- pkg:maven/io.prometheus.jmx/jmx_prometheus_javaagent@0.4
- pkg:maven/io.prometheus.jmx/jmx_prometheus_javaagent@0.4?classifier=sources
