- pkg:maven/org.opennms.alec.integrations.opennms/config@1.0.0
- pkg:maven/org.opennms.alec.integrations.opennms/config@1.0.0?classifier=sources
- pkg:maven/org.opennms.alec.integrations.opennms/config@1.0.1
- pkg:maven/org.opennms.alec.integrations.opennms/config@1.0.1?classifier=sources
