- pkg:maven/io.prometheus/simpleclient_dropwizard@0.0.12
- pkg:maven/io.prometheus/simpleclient_dropwizard@0.0.12?classifier=sources
- pkg:maven/io.prometheus/simpleclient_dropwizard@0.0.13
- pkg:maven/io.prometheus/simpleclient_dropwizard@0.0.13?classifier=sources
