- pkg:maven/com.github.traviscrawford/spark-dynamodb@0.0.2
- pkg:maven/com.github.traviscrawford/spark-dynamodb@0.0.2?classifier=sources
- pkg:maven/com.github.traviscrawford/spark-dynamodb@0.0.3
- pkg:maven/com.github.traviscrawford/spark-dynamodb@0.0.3?classifier=sources
