- pkg:maven/ch.jooel/config@1.0
- pkg:maven/ch.jooel/config@1.0?classifier=sources
- pkg:maven/ch.jooel/config@2.0
- pkg:maven/ch.jooel/config@2.0?classifier=sources
- pkg:maven/ch.jooel/config@3.1
- pkg:maven/ch.jooel/config@3.1?classifier=sources
- pkg:maven/ch.jooel/config@3.0
- pkg:maven/ch.jooel/config@3.0?classifier=sources
- pkg:maven/ch.jooel/config@3.2
- pkg:maven/ch.jooel/config@3.2?classifier=sources
