- pkg:maven/org.kie.server/kie-server-integ-tests-custom-extension-prometheus@7.26.0.Final
- pkg:maven/org.kie.server/kie-server-integ-tests-custom-extension-prometheus@7.26.0.Final?classifier=sources
- pkg:maven/org.kie.server/kie-server-integ-tests-custom-extension-prometheus@7.27.0.Final
- pkg:maven/org.kie.server/kie-server-integ-tests-custom-extension-prometheus@7.27.0.Final?classifier=sources
- pkg:maven/org.kie.server/kie-server-integ-tests-custom-extension-prometheus@7.28.0.Final
- pkg:maven/org.kie.server/kie-server-integ-tests-custom-extension-prometheus@7.28.0.Final?classifier=sources
