- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.1
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.1?classifier=sources
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.2
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.2?classifier=sources
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.3
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.3?classifier=sources
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.4
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.4?classifier=sources
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.1.0
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.1.0?classifier=sources
