- pkg:maven/io.earcam.maven.plugin/io.earcam.maven.plugin.netlify@0.0.1
- pkg:maven/io.earcam.maven.plugin/io.earcam.maven.plugin.netlify@0.0.1?classifier=sources
- pkg:maven/io.earcam.maven.plugin/io.earcam.maven.plugin.netlify@0.0.2
- pkg:maven/io.earcam.maven.plugin/io.earcam.maven.plugin.netlify@0.0.2?classifier=sources
