- pkg:maven/com.proofpoint.platform/reporting-prometheus@1.80
- pkg:maven/com.proofpoint.platform/reporting-prometheus@1.80?classifier=sources
- pkg:maven/com.proofpoint.platform/reporting-prometheus@1.79
- pkg:maven/com.proofpoint.platform/reporting-prometheus@1.79?classifier=sources
- pkg:maven/com.proofpoint.platform/reporting-prometheus@1.81
- pkg:maven/com.proofpoint.platform/reporting-prometheus@1.81?classifier=sources
- pkg:maven/com.proofpoint.platform/reporting-prometheus@1.82
- pkg:maven/com.proofpoint.platform/reporting-prometheus@1.82?classifier=sources
- pkg:maven/com.proofpoint.platform/reporting-prometheus@1.83
- pkg:maven/com.proofpoint.platform/reporting-prometheus@1.83?classifier=sources
- pkg:maven/com.proofpoint.platform/reporting-prometheus@1.84
- pkg:maven/com.proofpoint.platform/reporting-prometheus@1.84?classifier=sources
- pkg:maven/com.proofpoint.platform/reporting-prometheus@1.85
- pkg:maven/com.proofpoint.platform/reporting-prometheus@1.85?classifier=sources
- pkg:maven/com.proofpoint.platform/reporting-prometheus@1.86
- pkg:maven/com.proofpoint.platform/reporting-prometheus@1.86?classifier=sources
