- pkg:maven/org.wso2.ei/org.wso2.micro.integrator.prometheus.publisher.feature@1.1.0-alpha?classifier=sources
- pkg:maven/org.wso2.ei/org.wso2.micro.integrator.prometheus.publisher.feature@1.1.0-beta?classifier=sources
