- pkg:maven/io.micrometer.prometheus/prometheus-rsocket-client@0.8.0
- pkg:maven/io.micrometer.prometheus/prometheus-rsocket-client@0.8.0?classifier=sources
- pkg:maven/io.micrometer.prometheus/prometheus-rsocket-client@0.9.0
- pkg:maven/io.micrometer.prometheus/prometheus-rsocket-client@0.9.0?classifier=sources
