- pkg:maven/ch.sbb.releasetrain/config@0.0.23
- pkg:maven/ch.sbb.releasetrain/config@0.0.23?classifier=sources
- pkg:maven/ch.sbb.releasetrain/config@0.0.22
- pkg:maven/ch.sbb.releasetrain/config@0.0.22?classifier=sources
- pkg:maven/ch.sbb.releasetrain/config@0.0.21
- pkg:maven/ch.sbb.releasetrain/config@0.0.21?classifier=sources
- pkg:maven/ch.sbb.releasetrain/config@0.0.25
- pkg:maven/ch.sbb.releasetrain/config@0.0.25?classifier=sources
