- pkg:maven/org.apereo.cas/config@6.0.0-RC3
- pkg:maven/org.apereo.cas/config@6.0.0-RC3?classifier=sources
- pkg:maven/org.apereo.cas/config@6.0.0-RC4
- pkg:maven/org.apereo.cas/config@6.0.0-RC4?classifier=sources
- pkg:maven/org.apereo.cas/config@6.0.1
- pkg:maven/org.apereo.cas/config@6.0.1?classifier=sources
