- pkg:maven/com.networknt/prometheus@1.5.10
- pkg:maven/com.networknt/prometheus@1.5.10?classifier=sources
- pkg:maven/com.networknt/prometheus@1.5.11
- pkg:maven/com.networknt/prometheus@1.5.11?classifier=sources
