- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.11@1.1.9
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.11@1.1.9?classifier=sources
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.11@1.1.8
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.11@1.1.8?classifier=sources
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.11@1.1.7
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.11@1.1.7?classifier=sources
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.11@1.1.10
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.11@1.1.10?classifier=sources
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.11@1.1.11
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.11@1.1.11?classifier=sources
