- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@1.0.1
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@1.0.1?classifier=sources
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@1.0.2
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@1.0.2?classifier=sources
