- pkg:maven/net.vectorpublish/Config@0.9.26
- pkg:maven/net.vectorpublish/Config@0.9.26?classifier=sources
- pkg:maven/net.vectorpublish/Config@0.9.27
- pkg:maven/net.vectorpublish/Config@0.9.27?classifier=sources
