- pkg:maven/ru.lagoshny/docker-compose-maven-plugin@1.1
- pkg:maven/ru.lagoshny/docker-compose-maven-plugin@1.1?classifier=sources
- pkg:maven/ru.lagoshny/docker-compose-maven-plugin@1.0
- pkg:maven/ru.lagoshny/docker-compose-maven-plugin@1.0?classifier=sources
