- pkg:maven/io.micrometer/micrometer-prometheus-starter@0.6.3.RELEASE
- pkg:maven/io.micrometer/micrometer-prometheus-starter@0.6.3.RELEASE?classifier=sources
- pkg:maven/io.micrometer/micrometer-prometheus-starter@0.6.1.RELEASE
- pkg:maven/io.micrometer/micrometer-prometheus-starter@0.6.1.RELEASE?classifier=sources
- pkg:maven/io.micrometer/micrometer-prometheus-starter@0.8.0.RELEASE
- pkg:maven/io.micrometer/micrometer-prometheus-starter@0.8.0.RELEASE?classifier=sources
- pkg:maven/io.micrometer/micrometer-prometheus-starter@0.7.0.RELEASE
- pkg:maven/io.micrometer/micrometer-prometheus-starter@0.7.0.RELEASE?classifier=sources
- pkg:maven/io.micrometer/micrometer-prometheus-starter@0.9.1.RELEASE
- pkg:maven/io.micrometer/micrometer-prometheus-starter@0.9.1.RELEASE?classifier=sources
- pkg:maven/io.micrometer/micrometer-prometheus-starter@0.9.0.RELEASE
- pkg:maven/io.micrometer/micrometer-prometheus-starter@0.9.0.RELEASE?classifier=sources
- pkg:maven/io.micrometer/micrometer-prometheus-starter@0.9.2.RELEASE
- pkg:maven/io.micrometer/micrometer-prometheus-starter@0.9.2.RELEASE?classifier=sources
- pkg:maven/io.micrometer/micrometer-prometheus-starter@0.10.0.RELEASE
- pkg:maven/io.micrometer/micrometer-prometheus-starter@0.10.0.RELEASE?classifier=sources
