- pkg:maven/org.http4s/http4s-prometheus-metrics_2.12@0.19.0-M4
- pkg:maven/org.http4s/http4s-prometheus-metrics_2.12@0.19.0-M4?classifier=sources
- pkg:maven/org.http4s/http4s-prometheus-metrics_2.12@0.19.0
- pkg:maven/org.http4s/http4s-prometheus-metrics_2.12@0.19.0?classifier=sources
- pkg:maven/org.http4s/http4s-prometheus-metrics_2.12@0.20.0-M1
- pkg:maven/org.http4s/http4s-prometheus-metrics_2.12@0.20.0-M1?classifier=sources
