- pkg:maven/com.googlecode.openbox/config@1.0.0
- pkg:maven/com.googlecode.openbox/config@1.0.0?classifier=sources
- pkg:maven/com.googlecode.openbox/config@2.0.0
- pkg:maven/com.googlecode.openbox/config@2.0.0?classifier=sources
