- pkg:maven/org.lyranthe.prometheus/fs2_2.12@0.5.1
- pkg:maven/org.lyranthe.prometheus/fs2_2.12@0.5.1?classifier=sources
- pkg:maven/org.lyranthe.prometheus/fs2_2.12@0.5.0
- pkg:maven/org.lyranthe.prometheus/fs2_2.12@0.5.0?classifier=sources
