- pkg:maven/io.ap4k/prometheus-annotations@0.1.4
- pkg:maven/io.ap4k/prometheus-annotations@0.1.4?classifier=sources
- pkg:maven/io.ap4k/prometheus-annotations@0.2.0
- pkg:maven/io.ap4k/prometheus-annotations@0.2.0?classifier=sources
- pkg:maven/io.ap4k/prometheus-annotations@0.1.6
- pkg:maven/io.ap4k/prometheus-annotations@0.1.6?classifier=sources
- pkg:maven/io.ap4k/prometheus-annotations@0.1.5
- pkg:maven/io.ap4k/prometheus-annotations@0.1.5?classifier=sources
- pkg:maven/io.ap4k/prometheus-annotations@0.2.2
- pkg:maven/io.ap4k/prometheus-annotations@0.2.2?classifier=sources
- pkg:maven/io.ap4k/prometheus-annotations@0.2.1
- pkg:maven/io.ap4k/prometheus-annotations@0.2.1?classifier=sources
- pkg:maven/io.ap4k/prometheus-annotations@0.2.3
- pkg:maven/io.ap4k/prometheus-annotations@0.2.3?classifier=sources
