- pkg:maven/su.nlq/jmx-prometheus-collector@0.2
- pkg:maven/su.nlq/jmx-prometheus-collector@0.2?classifier=sources
- pkg:maven/su.nlq/jmx-prometheus-collector@0.1
- pkg:maven/su.nlq/jmx-prometheus-collector@0.1?classifier=sources
