- pkg:maven/de.weltraumschaf.commons/config@1.1.1
- pkg:maven/de.weltraumschaf.commons/config@1.1.1?classifier=sources
- pkg:maven/de.weltraumschaf.commons/config@1.1.0
- pkg:maven/de.weltraumschaf.commons/config@1.1.0?classifier=sources
