- pkg:maven/ro.pippo/pippo-metrics-prometheus@1.10.0
- pkg:maven/ro.pippo/pippo-metrics-prometheus@1.10.0?classifier=sources
- pkg:maven/ro.pippo/pippo-metrics-prometheus@1.11.0
- pkg:maven/ro.pippo/pippo-metrics-prometheus@1.11.0?classifier=sources
