- pkg:maven/org.lyranthe.prometheus/protobuf_2.11@0.4.0
- pkg:maven/org.lyranthe.prometheus/protobuf_2.11@0.4.0?classifier=sources
- pkg:maven/org.lyranthe.prometheus/protobuf_2.11@0.5.1
- pkg:maven/org.lyranthe.prometheus/protobuf_2.11@0.5.1?classifier=sources
- pkg:maven/org.lyranthe.prometheus/protobuf_2.11@0.5.0
- pkg:maven/org.lyranthe.prometheus/protobuf_2.11@0.5.0?classifier=sources
- pkg:maven/org.lyranthe.prometheus/protobuf_2.11@0.6.0
- pkg:maven/org.lyranthe.prometheus/protobuf_2.11@0.6.0?classifier=sources
