- pkg:maven/com.vectorprint/Config@1.1
- pkg:maven/com.vectorprint/Config@1.1?classifier=sources
- pkg:maven/com.vectorprint/Config@1.0
- pkg:maven/com.vectorprint/Config@1.0?classifier=sources
- pkg:maven/com.vectorprint/Config@1.6
- pkg:maven/com.vectorprint/Config@1.6?classifier=sources
- pkg:maven/com.vectorprint/Config@1.7
- pkg:maven/com.vectorprint/Config@1.7?classifier=sources
