- pkg:maven/com.adobe.aam/metrics-prometheus@1.0.2
- pkg:maven/com.adobe.aam/metrics-prometheus@1.0.2?classifier=sources
- pkg:maven/com.adobe.aam/metrics-prometheus@1.0.3
- pkg:maven/com.adobe.aam/metrics-prometheus@1.0.3?classifier=sources
