- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.3
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.3?classifier=sources
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.4
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.4?classifier=sources
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.5
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.5?classifier=sources
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.6
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.6?classifier=sources
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.7
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.7?classifier=sources
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.8
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.8?classifier=sources
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.9
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.9?classifier=sources
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.10
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.10?classifier=sources
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.1.0
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.1.0?classifier=sources
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.2.0
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.2.0?classifier=sources
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.3.0
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.3.0?classifier=sources
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.3.1
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.3.1?classifier=sources
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.11.0
- pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver@0.11.0?classifier=sources
