- pkg:maven/com.rnkrsoft.config/config@1.0.0
- pkg:maven/com.rnkrsoft.config/config@1.0.0?classifier=sources
- pkg:maven/com.rnkrsoft.config/config@1.0.1
- pkg:maven/com.rnkrsoft.config/config@1.0.1?classifier=sources
